### PR TITLE
Bundle the fonts instead of loading from google fonts (blenderskool#17)

### PR DESCRIPTION
**Pull request by gargakshit**
WRT #17

### CODE REVIEW

**Review by blenderskool — COMMENTED** [review]
Thanks for the PR @gargakshit! I haven't setup eslint and prettier config right now, but can we stick to using single quotes in the javascript file instead of double quotes?

**Comment by gargakshit** [comment]
I am really sorry about that, I didn't notice my defaults on prettier. Fixing the same

**Comment by gargakshit** [comment]
Fixed :)

**Review by blenderskool — APPROVED** [review]
Thank you for making the changes @gargakshit, I'm merging this PR.

**Comment by blenderskool** [comment]
Fixes #17

**Pull request merged**
